name: todo
description: A sample project for the treap package.

publish_to: 'none'

version: 1.0.0+1

environment:
  flutter: ^3.16.0
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter

  treap:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
   

flutter:
  uses-material-design: true