name: treap
description: A treap implementation in Dart.

version: 1.0.0
homepage: https://github.com/nielsenko/treap

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.17.5
