name: treap
description: >-
 A persistent treap for Dart.
 
 A heap balanced randomized binary tree with efficient value semantics.
 
topics:
  - treap
  - data-structures
  - collections
  - functional

version: 0.2.0 # still some planned interface changes
homepage: https://github.com/nielsenko/treap

environment:
  sdk: ^3.4.0

dev_dependencies:
  benchmark_harness: ^2.2.2
  lints: ^4.0.0
  test: ^1.17.5
