name: treap
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/nielsenko/treap

environment:
  sdk: '>=2.13.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.17.5
