name: treap
description: >-
 A persistent treap for Dart.
 
 A heap balanced randomized binary tree with efficient value semantics.
 All operations are O(log n) worst case.

version: 1.0.0
homepage: https://github.com/nielsenko/treap

environment:
  sdk: ^3.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.17.5
