name: treap
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/nielsenko/treap

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  pedantic: ^1.11.0

dev_dependencies:
  test: ^1.17.5
